### ISSUE TITLE
create AnswerSets class

### ISSUE THREAD

**Issue by stefanogermano** [dave90/ANDLV#1]
There should be a class `AnswerSets` that is a container of `AnswerSet`, that for the moment it should contain only a collection of `AnswerSet` and the methods to access it

**Comment by brainatwork** [comment]
AnswerSets class created and i have added first methods [at](https://github.com/dave90/ANDLV/commit/d4a0d48a4127f28fd9c8ba6604f03e83be1e2e98)

**Comment by brainatwork** [comment]
Other methods added [at](https://github.com/dave90/ANDLV/commit/c0fb2ddf99e20ee38a40d6f7e64efbbdb59ff242). For now i will attend a feedback and i will try to solve the DLVService class commit error.

**Comment by brainatwork** [comment]
public void setAnswerSets(String answerSets) {
        this.answerSets = answerSets;
this.parse(answerSets);//create and insert AnswerSet objects in the AnswerSet ArrayList
    }

parse is an abstract method. Is it the right idea to put parse() method after the answerSets String?
