### ISSUE TITLE
DLV name

### ISSUE THREAD

**Issue by stefanogermano** [dave90/ANDLV#10]
DLV should be written always with all caps (also in class names, **keep attention** that on Windows when you change the case of a letter in a filename it'll not "really rename" it)

**Comment by brainatwork** [comment]
there are many problems changing class names. For DlvService class is not possible becase generate an error with the native func.
Change DlvHandler name to DLVHandler generate an error when i commit the project to githubbut not in the project.

**Comment by brainatwork** [comment]
I think the last problem for DLVHandler class name is solved.

**Comment by stefanogermano** [comment]
After you close the issue #4, @dave90 will compile for you the new version (renamed) of  `DLVService` (to put in the package _andlv.dlv_)

**Comment by brainatwork** [comment]
New packages hierarchy Added:

it.unical.mat.andlv/
|-base/
     |-AnswerSetCallback
     |-ASPHandler
     |-ASPService
|-dlv/
     |-DLVHandler
     |-DLVService
|-AnswerSet
|-CallBackProva
|-MainActivity
|-OutputReceiver

**Comment by brainatwork** [comment]
Sorry!There are errors in the format. My fault. Maybe you can see clearly [at](https://github.com/dave90/ANDLV/commit/d865fe8bb14d22b506011c3e401b041734df846a)

**Comment by brainatwork** [comment]
Commit error on DLVService. 
Error:error: pathspec 'app/src/main/java/it/unical/mat/andlv/dlv/DLVService.java' did not match any file(s) known to git.
 during executing git commit --only -F C:\Users\Dario\AppData\Local\Temp\git-commit-msg-7210103402840324891.txt -- app/src/main/java/it/unical/mat/andlv/dlv/DLVService.java

**Comment by brainatwork** [comment]
Problem solved. Now in there is  a DLVService file in repo.
