### ISSUE TITLE
abstract AnswerSet

### ISSUE THREAD

**Issue by stefanogermano** [dave90/ANDLV#15]
`AnswerSet` should be an abstract class because `getAnswerObjects()` should be different for different solver

**Comment by stefanogermano** [comment]
Or we can add in `AnswerSet` a `List` of _atoms_ (as `String`) that will be filled by the `parse` method of the `AnswerSets` class

**Comment by dave90** [comment]
474103c8e05075baa9103c963e367ee51a14a709
