### ISSUE TITLE
Throw exceptions in ASPHandler

### ISSUE THREAD

**Issue by stefanogermano** [dave90/ANDLV#17]
In the class `ASPHandler`, `addInput(final Object inputObj)` and `addInput(final Set<Object> inputObjs)` should `throw` the exceptions and not `catch` them

**Comment by stefanogermano** [comment]
Also `addFileInput(final String filePath)` should

**Comment by jessicazangari** [comment]
Already done. Check the last commit bf127200386d5879d284b32c2c752888ba1fba5c

**Comment by stefanogermano** [comment]
I think we should add also in `addFileInput(final String filePath)`

**Comment by dave90** [comment]
354f9f87548364c17497aab6112c5c8fcbb60799
