### ISSUE TITLE
New packages

### ISSUE THREAD

**Issue by stefanogermano** [dave90/ANDLV#4]
Inside the _andlv_ package, there should package for the base classes (_base_) and a package for derived classes (_dlv_)

**Comment by brainatwork** [comment]
I have created a new hierarchy, commit [at](https://github.com/dave90/ANDLV/commit/d865fe8bb14d22b506011c3e401b041734df846a)

The OutputReceiver is a derived class from BroadcastReceiver. I have to insert OutputReceiver class in it.unical.mat.andlv.dlv package?

**Comment by stefanogermano** [comment]
`OutputReceiver` should be in _base_,
also `AnswerSet` should be in _base_.

**Comment by brainatwork** [comment]
Ok. I'll make changes soon and i'll send commit link.

**Comment by brainatwork** [comment]
[commit](https://github.com/dave90/ANDLV/commit/8a4ff1d0574d1f29d227cefebd3f02bd6247d108) with changes. Can i cose the issue? In this case
@dave90, when it is possible, can you send me a re-compiled version of the .so library?
