### ISSUE TITLE
Good programming practice with abstract classes

### ISSUE THREAD

**Issue by stefanogermano** [dave90/ANDLV#7]
When create a new instance of a class, you should use the base class in the definition and the derived (concrete) class in the instantiation (**not** `CallbackProva callb = new CallbackProva();` but `AnswerSetCallback callb = new CallbackProva();`)

**Comment by brainatwork** [comment]
changed code line in AnswerSetCallback callb = new CallbackProva();

**Comment by dave90** [comment]
Please use comment only if you have any doubt of issue. To report how you solved do a commit. When you're sure you have completed 100% the issue you can close issue.

**Comment by stefanogermano** [comment]
The one posted above was only an example, you should do the same in all the part of the code where you are instantiating a derived class (for instance, but I think this is not the only one, `DLVHandler DLVHandler = new DLVHandler();`)

Please **double check** before closing an issue (otherwise we'll lose a lot of time checking your work).

When you close an issue, it's better to link to the commit in which we can see what you did (otherwise we'll lose a lot of time looking for it).
If you don't know how to do this please have a look [at](https://guides.github.com/features/mastering-markdown)

**Comment by brainatwork** [comment]
[link to commit that have to solve the issue](https://github.com/dave90/ANDLV/commit/d7926474d188d205bf9eea80f7c568118798c680)
