### ISSUE TITLE
Context in ASPHandler

### ISSUE THREAD

**Issue by stefanogermano** [dave90/ANDLV#8]
We should avoid to refer to `Context` in `ASPHandler` (we have to investigate on how to achieve this), but if it's not possible (**double check this!**), we should use the `ApplicationContext`and not the `Activity` to avoid [memory leaks](http://android-developers.blogspot.it/2009/01/avoiding-memory-leaks.html). Moreover if it's not possible to avoid it (**check it again**), the `Context` should be passed as parameter of the `start` function.

**Comment by brainatwork** [comment]
Now Context is a start() func parameter.

**Comment by stefanogermano** [comment]
**There is no commit**

Have you used `ApplicationContext` instead of `Activity`?

Have you (triple) checked that it is no way to avoid the use of `Context`?

**Comment by brainatwork** [comment]
Context in Android is necessary for some functions and pass it to construtor or start function seems a good idea. This kind of solution is used in Android development.
